Slew
NSF-Swift/satellite-overhead pull request #25
Opened 2023-04-25 16:36 UTC by ellem95

Adding the ability to calculate satellites as antenna moves across sky

2023-04-28 21:56 UTC, nikojpapa commented
This is based on the `window_finder` branch, right? Can you change the base of the PR to reflect that so we are not reviewing duplicate changes?

2023-05-02 17:09 UTC, nikojpapa requested changes

2023-05-02 17:09 UTC, nikojpapa commented on satellite_determination/path_finder/observation_path_finder.py
> +        #end_time = self._reservation.time.end
```suggestion
```

2023-05-11 09:29 UTC, ellem95 commented on expected_path.txt
done

2023-05-11 09:29 UTC, ellem95 commented on satellite_determination/TLEData/test.txt
removed

2023-05-11 09:31 UTC, ellem95 commented on satellite_determination/custom_dataclasses/observation_path.py
Deleted unnecessary function

2023-05-11 09:33 UTC, ellem95 commented on satellite_determination/path_finder/observation_path_finder.py
> +        #end_time = self._reservation.time.end
done

2023-05-11 09:34 UTC, ellem95 commented on satellite_determination/window_finder.py
> +        return self._event_finder(list_of_satellites=self._satellites, reservation=reservation, azimuth_altitude_path=None).get_overhead_windows()
WindowFinder is only used if we are doing stationary observations so does not have a ```azimuth_altitude_path```

2023-05-12 16:37 UTC, ellem95 commented on satellite_determination/event_finder/event_finder_rhodesmill/event_finder_rhodesmill.py
> +        time_end = ts.from_datetime(self._reservation.time.end.replace(tzinfo=pytz.UTC))
Resolved

2023-05-12 19:42 UTC, ellem95 commented on satellite_determination/event_finder/event_finder_rhodesmill/event_finder_rhodesmill.py
> +        time_end = ts.from_datetime(self._reservation.time.end.replace(tzinfo=pytz.UTC))
Messaged in slack. If you look at the code at this file and these line numbers, you'll see its been updated. The other instances are all updated in PR #27 where they were commented on.

2023-05-12 22:48 UTC, nikojpapa approved these changes

2023-05-13 04:30 UTC, merged