Sopp and tle fetcher edits
NSF-Swift/satellite-overhead pull request #29
Opened 2023-05-11 20:32 UTC by ellem95

2023-05-11 21:01 UTC, nikojpapa requested changes

2023-05-15 21:16 UTC, ellem95 commented on utilities.py
Moved

2023-05-15 21:45 UTC, ellem95 commented on utilities.py
> +    return Path(os.path.dirname(os.path.abspath(__file__)))
Made this change and use `get_supplements_directory` in the TleFetcher now.

2023-05-15 21:45 UTC, ellem95 commented on utilities.py
> +def get_root_directory(module) -> Path:
Changed

2023-05-15 21:46 UTC, ellem95 commented on utilities.py
> +def get_root_directory(module) -> Path:
Changed

2023-05-16 17:08 UTC, nikojpapa approved these changes

2023-05-16 17:46 UTC, merged